### PR TITLE
Adding hall of fame

### PR DESCRIPTION
**Pull request by RajGhugare19**

### CODE REVIEW

**Comment by take2rohit** [comment]
Change to devel @RajGhugare19

**Comment by RajGhugare19** [comment]
@take2rohit done

**Comment by take2rohit** [comment]
It has become very difficult to trace changes as you modified the whole readme. No issue. You can do one thing as well.

http://markdowntable.com/
Use this to properly format all tables so that it looks better and becomes a readable markdown

**Review by akshaykvnit — APPROVED** [review]

**Comment by take2rohit** [comment]
I m closing this PR. Make sure to raise this issue 

> It has become very difficult to trace changes as you modified the whole readme. No issue. You can do one thing as well. http://markdowntable.com/ Use this to properly format all tables so that it looks better and becomes a readable markdown

**Pull request merged**
