### PR TITLE
Paper notes of Dynamics and Controls

### PR DESCRIPTION
**Pull request by saad2121**

### CODE REVIEW

**Comment by akshaykvnit** [comment]
Add columns for dates as well. Make it consistent with other folders. If you don't remember the dates, you can go in Hackmd and see the version history and figure out the starting and ending date from there.

**Comment by take2rohit** [comment]
It seems equations arent rendered! 
in `Notes on: Real-Time Obstacle Avoidance for Manipulators and Mobile Robots` 
Please check and let me know (use `$ ...$` for inline equations)

image

**Comment by saad2121** [comment]
it takes time and good network to render.
Screenshot (47)

**Comment by take2rohit** [comment]
Merging this PR due to no response on Discord about its review.
Feel free to reopen this PR.

**Pull request merged**
