### PR TITLE
Added yolo paper annotated pdf notes

### PR DESCRIPTION
**Pull request by take2rohit**
Let me know if annotated pdf is allowed or not

### CODE REVIEW

**Comment by RajGhugare19** [comment]
@take2rohit As of now it isn't decided. But a decision will be taken shortly accounting the responses of today's form on discord.

**Comment by sakethbachu** [comment]
@take2rohit In terms of content, it looks good according to me.

**Comment by take2rohit** [comment]
@RajGhugare19 @aditya-shirwatkar any decision on this?

**Comment by RajGhugare19** [comment]
Ig it is okay.

**Review by RajGhugare19 — APPROVED** [review]

**Pull request merged**
